### ISSUE TITLE
Better colour styling

### ISSUE THREAD

**Issue by James-Ashwood** [The-Intil-Coding-Group/SRunner#4]
Better colour styling, to make the game more visually pleasing
Version: 1.1

**Comment by James-Ashwood** [comment]
It would be nice to have improved images

**Comment by James-Ashwood** [comment]
@C0ding4life, when you do the pool image, please can you leave it empty, as I will fill the image with other particles that will help with the programing for issue #2 . Basically, I just need an empty container.

**Comment by James-Ashwood** [comment]
Looking back, rather than working on a pool I will add more, but different blocks

**Comment by C0ding4life** [comment]
![pixil-layer-Layer 1](https://user-images.githubusercontent.com/79657778/128623796-3ebfbf97-5537-4bd9-b080-95c0667816e6.png)
The character
![pixil-frame-0](https://user-images.githubusercontent.com/79657778/128623797-6204689b-e2ff-4d81-bd86-6aecf00b125c.png)
THe Platform

**Comment by James-Ashwood** [comment]
Nice work. There is one white pixel that you missed on the character but apart from that it is great. Is it possible that you could provide the pixel dimensions and for each block (like the platform and the jumper and the bridge, etc...) that you could keep them the same width. Thanks a lot for helping out though, @C0ding4life

**Comment by C0ding4life** [comment]
![pixil-frame-0 (2)](https://user-images.githubusercontent.com/79657778/128625999-0841aa45-dc97-440a-9789-52333bfcddc4.png)
- New edited character
- Platform 200 x 60
- Character 50 x 50

**Comment by James-Ashwood** [comment]
Thanks @C0ding4life

**Comment by C0ding4life** [comment]
![pixil-frame-0 (3)](https://user-images.githubusercontent.com/79657778/128626633-3c3862b9-cc19-41cf-a5fb-ac2875eb0ca7.png)
spring
200 x 100

**Comment by James-Ashwood** [comment]
Nice work @C0ding4life

**Comment by C0ding4life** [comment]
![pixil-frame-0 (4)](https://user-images.githubusercontent.com/79657778/128626790-c4c1be81-ac8c-4731-a421-5788ef3537a8.png)
new colouring for the platform

**Comment by James-Ashwood** [comment]
> 
> 
> ![pixil-frame-0 (4)](https://user-images.githubusercontent.com/79657778/128626790-c4c1be81-ac8c-4731-a421-5788ef3537a8.png)
> new colouring for the platform

Nice work

**Comment by James-Ashwood** [comment]
Bridge - Increased friction compaered to the floor
Hill - Differently shaped, same physics properties as the floor
Zapper - Impulses you slightly up and dramatically to the right

**Comment by C0ding4life** [comment]
![pixil-frame-0 (5)](https://user-images.githubusercontent.com/79657778/128627020-5fd8aafc-8f9e-437c-8489-ad9b29364ff6.png)
Sludge
The bridge i guess
Slows you down

**Comment by James-Ashwood** [comment]
Good work @C0ding4life

**Comment by James-Ashwood** [comment]
This was excellent work @C0ding4life. Thanks so much for you help.
